spa/urls.py
from django.urls import path, include
import allauth.account
from . import views

urlpatterns = [
	path('accounts/signup/', views.student_registration, name='account_signup'),
	path('accounts/login/', views.login, name='account_login'),
	# path('accounts/login/', allauth.account.views.LoginView.as_view(), name='account_login'),
	path('accounts/', include('allauth.account.urls')),
	path('', views.redirect_to_dashboard, name='redirect_to_dashboard'),
	path('<int:pk>/', views.student_dashboard, name='student_dashboard'),
	path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
	path('register-project/', views.register_project, name='register_project'),
	path('project/<int:pk>/', views.project_detail, name='project_detail'),
	path('project-update/<int:pk>/', views.project_update, name='project_update'),
	path('project-delete/<int:pk>/', views.project_delete, name='project_delete'),
	path('project-list/', views.project_list, name='project_list'),
	path('student-list/', views.student_list, name='student_list'),
	path('student-update/<int:pk>/', views.student_update, name='student_update')
]

student_allocation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spa.urls')),
]

spa/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

User = settings.AUTH_USER_MODEL

# Create your models here.

class Project(models.Model):
	title = models.CharField(max_length=200)
	case_study = models.CharField(max_length=200)

	def __str__(self):
		return self.title

	@property
	def allocated(self):
		if self.student_set.all().count() > 0:
			return True
		return False

	@property
	def group_project(self):
		if self.student_set.all().count() > 1:
			return True
		return False

class Student(models.Model):
	DEPARTMENTS = (
		('Agricultural Engineering', 'Agricultural Engineering'),
		('Electrical Engineering', 'Electrical Engineering'),
		('Computer Engineering', 'Computer Engineering'),
		('Chemical Engineering', 'Chemical Engineering'),
		('Petroleum Engineering', 'Petroleum Engineering'),
		('Mechanical Engineering', 'Mechanical Engineering'),
		('Food Engineering', 'Food Engineering'),
		('Civil Engineering', 'Civil Engineering'),
	)

	LEVEL = (
		('500 Level', '500 Level'),
		('Spill Over', 'Spill Over'),
	)

	user = models.OneToOneField(User, on_delete=models.CASCADE)
	reg_no = models.CharField(max_length=50)
	department = models.CharField(max_length=100, choices=DEPARTMENTS)
	level = models.CharField(max_length=50, choices=LEVEL, default='500 Level')
	project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)
	date_joined = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return f'{self.user.first_name} {self.user.last_name}'

spa/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from allauth.account.forms import SignupForm
from .models import Student, Project

# User = settings.AUTH_USER_MODEL

class UserRegistrationForm(SignupForm):
	first_name = forms.CharField(max_length=200)
	last_name = forms.CharField(max_length=200)
	# email = forms.EmailField()
	class Meta:
		model = User 
		fields = ['first_name', 'last_name', 'email']
		# fields = '__all__'

class StudentForm(forms.ModelForm):
	class Meta:
		model = Student 
		fields = ['reg_no', 'department', 'level']

class LoginForm(forms.Form):
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput)

class UserForm(forms.ModelForm):
	class Meta:
		model = User 
		fields = ['first_name', 'last_name', 'email']

class ProjectForm(forms.ModelForm):
	class Meta:
		model = Project 
		fields = ['title', 'case_study']

# class UserRegisterForm(UserRegistrationForm):
# 	class Meta:
# 		model = User 
# 		fields = ['']

spa/views.py
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views import generic
from django.contrib.auth.models import User
from django.views.generic.base import TemplateResponseMixin
from django.contrib import messages
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from allauth.account.views import SignupView
from django.db.models import Q
from .forms import LoginForm

from .forms import UserRegistrationForm, StudentForm, UserForm, ProjectForm
from .mixins import RedirectLoggedInUser, StaffRequiredMixin
from .models import Student, Project

# Create your views here.

class StudentRegistrationView(RedirectLoggedInUser, generic.TemplateView):
	template_name = 'account/signup.html'
	def get(self, request, *args, **kwargs):
		# Pass User Registration Form and Student Form
		u_form = UserRegistrationForm()
		s_form = StudentForm()
		context = {
			'u_form': u_form,
			's_form': s_form,
		}
		return self.render_to_response(context)

	def post(self, request, *args, **kwargs):
		# Get User Data From The Form
		u_form = UserRegistrationForm(request.POST)
		s_form = StudentForm(request.POST)
		if u_form.is_valid() and s_form.is_valid(): # If The Two Form Input Are Valid
			# Save The Two Forms And Redirect User To Login
			u_form.save(request)
			u_email = u_form.cleaned_data['email']
			user = User.objects.get(email=u_email)
			s_form = s_form.save(commit=False)
			s_form.user = user 
			s_form.save()
			messages.success(request, "Your Account Has Been Created. You Can Now Login")
			return redirect('account_login')
		# If Not Valid Render Sign Up Page With Form And Error
		context = {
			'u_form': u_form,
			's_form': s_form,
		}
		return self.render_to_response(context)

student_registration = StudentRegistrationView.as_view()

class LoginView(RedirectLoggedInUser, generic.TemplateView):
	template_name = 'account/login.html'
	def get(self, request, *args, **kwargs):
		# Pass Login Form
		form = LoginForm()
		return self.render_to_response({'form': form})

	def post(self, request, *args, **kwargs):
		# Get User Data From The Form
		form = LoginForm(request.POST)
		if form.is_valid(): # Form is valid
			data = form.cleaned_data
			email = data['email']
			if User.objects.filter(email=email).exists(): # Check if user with email exists
				username = User.objects.get(email=email).username
			else:
				messages.error(request, 'Email doesn\'t exist')
				return self.render_to_response({'form': form})
			password = data['password']
			# Authenticate user
			user = auth.authenticate(username=username, password=password)
			if user is not None: # Checks if user exist
				auth.login(request, user)
				return redirect(reverse('student_dashboard', kwargs={'pk': user.pk}))
		messages.error(request, "Incorrect password")
		return self.render_to_response({'form': form})

login = LoginView.as_view()

class RedirectToDashboard(View):
	def dispatch(self, request, *args, **kwargs):
		if request.user.is_authenticated:
			return redirect(reverse('student_dashboard', kwargs={'pk': request.user.pk}))
		return redirect('account_login')

redirect_to_dashboard = RedirectToDashboard.as_view()


class StudentDashboardView(LoginRequiredMixin, generic.TemplateView):
	template_name = 'spa/student-dashboard.html'

	def dispatch(self, request, *args, **kwargs):
		if request.user.is_staff:
			return redirect('admin_dashboard') 
		return super().dispatch(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		# Pass Forms 
		context = super().get_context_data(*args, **kwargs)
		context['u_form'] = UserForm()
		context['s_form'] = StudentForm()
		context['p_form'] = ProjectForm()
		context['user'] = User.objects.get(pk=kwargs['pk'])
		return context

student_dashboard = StudentDashboardView.as_view()

class StudentUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
	template_name = 'spa/student-update.html'

	def post(self, request, *args, **kwargs):
		# Save Updates
		user = User.objects.get(pk=kwargs['pk'])
		u_form = UserForm(request.POST, instance=user)
		s_form = StudentForm(request.POST, instance=user.student)
		if u_form.is_valid():
			u_form.save()
			s_form.save()
			return redirect(reverse('student_dashboard', kwargs={'pk': kwargs['pk']}))
		return self.render_to_response({"u_form": u_form, 's_form': s_form})

	def get_context_data(self, *args, **kwargs):
		# Pass Forms 
		context = super().get_context_data(*args, **kwargs)
		context['u_form'] = UserForm()
		context['s_form'] = StudentForm()
		context['user'] = User.objects.get(pk=kwargs['pk'])
		return context

	def test_func(self):
		return User.objects.get(pk=self.kwargs['pk']) == self.request.user or self.request.user.is_staff

student_update = StudentUpdateView.as_view()

class AdminDashboardView(LoginRequiredMixin, generic.TemplateView):
	template_name = 'spa/admin-dashboard.html'

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return redirect(reverse('student_dashboard', kwargs={'pk': request.user.pk})) 
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		# Save Updates
		u_form = UserForm(request.POST, instance=request.user)
		if u_form.is_valid():
			u_form.save()
			return redirect('admin_dashboard')
		return self.render_to_response({'u_form': u_form})

	def get_context_data(self, *args, **kwargs):
		# Pass Forms
		context = super().get_context_data(*args, **kwargs)
		context['u_form'] = UserForm()
		return context

admin_dashboard = AdminDashboardView.as_view()

def project_post_action(self, request, action, pk=None):
	# Get Data
		form = ProjectForm(request.POST) if action == 'register' else ProjectForm(request.POST, instance=Project.objects.get(pk=pk))
		if form.is_valid():
			data = form.cleaned_data
			title = data['title']
			case_study = data['case_study']
			
			title_exist = Project.objects.filter(title=title).exists() if action == 'register' else Project.objects.exclude(pk=pk).filter(title=title).exists()
			case_study_exist = Project.objects.filter(case_study=case_study).exists() if action == 'register' else Project.objects.exclude(pk=pk).filter(case_study=case_study).exists()
			# If project exists, flag user
			if title_exist or case_study_exist:
				messages.error(request, 'This Project Has Been Allocated')
				return self.render_to_response({'form': form})
			# If group members are added
			try:
				students = list(map(lambda x: int(x), request.POST.getlist('students')))
				if action == 'register':
					for student_id in students:
						student = Student.objects.get(pk=student_id)
						if student.project is not None:
							# If one of the group members is in a project
							messages.error(request, 'Project Has Already Been Allocated To One Of The Group Members')
							form_data = {
								'title': title,
								'case_study': case_study,
								'students_id':students, 
							}
							context = {
								'form': form,
								'students': Student.objects.exclude(user=self.request.user),
								'form_data': form_data,
							}
							return self.render_to_response(context)
			except:
				pass
			# Save project and associate it with user
			form.save()
			project = Project.objects.get(title=title)

			if action == 'register':
				if not request.user.is_staff:
					request.user.student.project = project
					request.user.student.save()
				try:
					for student_id in students:
						# Associate group members to project
						student = Student.objects.get(pk=int(student_id))
						student.project = project
						student.save()
				except:
					pass
			else:
				try:
					for student in project.student_set.all():
						student.project = None
						student.save()
					for student_id in students:
						# Associate group members to project
						student = Student.objects.get(pk=int(student_id))
						student.project = project
						student.save()
				except:
					pass 

			return redirect(reverse('project_detail', args=[project.pk]))
		return self.render_to_response({'form': form})

class RegisterProjectView(LoginRequiredMixin, generic.TemplateView):
	template_name = 'spa/register-project.html'

	def post(self, request, *args, **kwargs):
		return project_post_action(self, request, action='register')
			

	def get_context_data(self, *args, **kwargs):
		# Pass Forms
		context = super().get_context_data(*args, **kwargs)
		context['form'] = ProjectForm()
		context['students'] = Student.objects.exclude(user=self.request.user)
		return context 

register_project = RegisterProjectView.as_view()

class ProjectDetailView(LoginRequiredMixin, generic.TemplateView):
	template_name = 'spa/project-detail.html'

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		project = Project.objects.get(pk=kwargs['pk'])
		context['project'] = project
		context['form'] = ProjectForm(instance=project)
		context['students'] = Student.objects.all()
		return context

project_detail = ProjectDetailView.as_view()

class ProjectUpdateview(LoginRequiredMixin, UserPassesTestMixin, generic.TemplateView):
	template_name = 'spa/project-update.html'
	project = None

	def dispatch(self, request, *args, **kwargs):
		self.project = Project.objects.get(pk=kwargs['pk'])
		return super().dispatch(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		return project_post_action(self, request, 'update', pk=kwargs['pk'])

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		# project = Project.objects.get(pk=kwargs['pk'])
		context['project'] = self.project

spa/templates/spa/admin-dashboard.html
{% extends 'base.html' %}

{% block title %}Your Dashboard{% endblock title %}

{% block content %}
	<h2 class="text-center mt-4 mb-3">Admin Dashboard</h2>
	<div class="row">
		<div class="col-lg-6">
			<div class="p-4">
				<h5 class="mb-2">Your Profile:</h5>
				<form method="post">
					{% csrf_token %}
					<div>
						{% if u_form.non_field_errors %}
							<ol>
								{% for error in u_form.non_field_errors %}
									<li><strong>{{error|escape}}</strong></li>
								{% endfor %}
							</ol>
						{% endif %}
					</div>
					<div class="fieldWrapper form-group">
						<div class="form-group">
							<input type="text" name="first_name" id="id_first_name" placeholder="First Name" class="form-control" value="{{request.user.first_name}}">
							<i class="fa-solid fa-circle-user input-icon"></i>
						</div>
						{% if u_form.first_name.errors %}
							<ul class="list-unstyled" style="margin-top: -0.9rem;">
								{% for error in u_form.first_name.errors %}
									<li class="text-danger font-italic small">{{error | escape}}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
					<div class="fieldWrapper form-group">
						<div class="form-group">
							<input type="text" name="last_name" id="id_last_name" placeholder="Last Name" class="form-control" value="{{request.user.last_name}}">
							<i class="fa-solid fa-circle-user input-icon"></i>
						</div>
						{% if u_form.last_name.errors %}
							<ul class="list-unstyled" style="margin-top: -0.9rem;">
								{% for error in u_form.last_name.errors %}
									<li class="text-danger font-italic small">{{error | escape}}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
					<div class="fieldWrapper form-group">
						<div class="form-group">
							<input type="email" name="email" id="id_email" placeholder="Email" class="form-control" value="{{request.user.email}}">
							<i class="fa-solid fa-envelope input-icon"></i>
						</div>
						{% if u_form.email.errors %}
							<ul class="list-unstyled" style="margin-top: -0.9rem;">
								{% for error in u_form.email.errors %}
									<li class="text-danger font-italic small">{{error | escape}}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
					<button class="btn btn-primary" type="submit">Update</button>
				</form>
			</div>
		</div>
		<div class="col-lg-6"></div>
	</div>

{% endblock content %}

spa/templates/spa/dashboard.html
{% extends 'base.html' %}

{% block title %}Your Dashboard{% endblock title %}

{% block content %}
	
	<div class="d-flex flex-column align-items-center">
		<h2 class="text-center mt-4 mb-3">Dashboard</h2>
		<div class="bg-white p-4 shadow" style="min-width: 500px;">
			<h5 class="mb-2">Your Profile:</h5>
			<form method="post">
				{% csrf_token %}
				<div>
					{% if u_form.non_field_errors %}
						<ol>
							{% for error in u_form.non_field_errors %}
								<li><strong>{{error|escape}}</strong></li>
							{% endfor %}
						</ol>
					{% endif %}
					{% if s_form.non_field_errors %}
						<ol>
							{% for error in s_form.non_field_errors %}
								<li><strong>{{error|escape}}</strong></li>
							{% endfor %}
						</ol>
					{% endif %}
				</div>
				<div class="fieldWrapper form-group">
					<div class="form-group">
						<input type="text" name="first_name" id="id_first_name" placeholder="First Name" class="form-control" value="{{request.user.first_name}}">
						<i class="fa-solid fa-circle-user input-icon"></i>
					</div>
					{% if u_form.first_name.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in u_form.first_name.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				<div class="fieldWrapper form-group">
					<div class="form-group">
						<input type="text" name="last_name" id="id_last_name" placeholder="Last Name" class="form-control" value="{{request.user.last_name}}">
						<i class="fa-solid fa-circle-user input-icon"></i>
					</div>
					{% if u_form.last_name.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in u_form.last_name.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				<div class="fieldWrapper form-group">
					<div class="form-group">
						<input type="text" name="reg_no" id="id_reg_no" placeholder="Reg No" class="form-control"  value="{{request.user.student.reg_no}}">
						<i class="fa-solid fa-circle-user input-icon"></i>
					</div>
					{% if s_form.reg_no.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in s_form.reg_no.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>

				<div class="fieldWrapper form-group">
					<div class="form-group">
						
						<select name="department" id="id_department" required class="form-control">
							<option value="">Department</option>
							<option value="Agricultural Engineering">Agricultural Engineering</option>
							<option value="Electrical Engineering">Electrical Engineering</option>
							<option value="Computer Engineering">Computer Engineering</option>
							<option value="Petroleum Engineering">Petroleum Engineering</option>
							<option value="Chemical Engineering">Chemical Engineering</option>
							<option value="Mechanical Engineering">Mechanical Engineering</option>
							<option value="Food Engineering">Food Engineering</option>
							<option value="Civil Engineering">Civil Engineering</option>
						</select>
						<i class="fa-regular fa-address-card input-icon"></i>
					</div>
					{% if s_form.department.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in s_form.department.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				<div class="fieldWrapper form-group">
					<div class="form-group">
						<select name="level" id="id_level" required class="form-control">
							<option value="">Level</option>
							<option value="500 Level">500 Level</option>
							<option value="Spill Over">Spill Over</option>
						</select>
						<i class="fa-regular fa-address-card input-icon"></i>
					</div>
					{% if s_form.level.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in s_form.level.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				<div class="fieldWrapper form-group">
					<div class="form-group">
						<input type="email" name="email" id="id_email" placeholder="Email" class="form-control" value="{{request.user.email}}">
						<i class="fa-solid fa-envelope input-icon"></i>
					</div>
					{% if u_form.email.errors %}
						<ul class="list-unstyled" style="margin-top: -0.9rem;">
							{% for error in u_form.email.errors %}
								<li class="text-danger font-italic small">{{error | escape}}</li>
							{% endfor %}
						</ul>
					{% endif %}
				</div>
				<button class="btn btn-primary" type="submit">Update</button>
			</form>

			{% if request.user.student.project is None %}

				<div class="d-flex flex-column align-items-center mt-4">
					<h6>You Have Not Registered Your Project</h6>
					<a href="{% url 'register_project' %}" class="btn btn-success">Register Now</a>
				</div>

			{% else %}

				<h5 class="mt-5 mb-2">Your Project:</h5>
				<form method="post">
					{% csrf_token %}
					<div>
						{% if p_form.non_field_errors %}
							<ol>
								{% for error in p_form.non_field_errors %}
									<li><strong>{{error|escape}}</strong></li>
								{% endfor %}
							</ol>
						{% endif %}
					</div>
					<div class="fieldWrapper form-group">
						<label for="{{p_form.title.id_for_title}}">Title</label>
						<div class="form-group">
							<input type="text" name="title" id="id_title" class="form-control" value="{{request.user.student.project.title}}">
							<i class="fa-solid fa-circle-user input-icon"></i>
						</div>
						{% if p_form.title.errors %}
							<ul class="list-unstyled" style="margin-top: -0.9rem;">
								{% for error in p_form.title.errors %}
									<li class="text-danger font-italic small">{{error | escape}}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
					<div class="fieldWrapper form-group">
						<label for="{{p_form.case_study.id_for_case_study}}">Case Study</label>
						<div class="form-group">
							<input type="text" name="case_study" id="id_case_study" class="form-control" value="{{request.user.student.project.case_study}}">
							<i class="fa-solid fa-circle-user input-icon"></i>
						</div>
						{% if p_form.case_study.errors %}
							<ul class="list-unstyled" style="margin-top: -0.9rem;">
								{% for error in p_form.case_study.errors %}
									<li class="text-danger font-italic small">{{error | escape}}</li>
								{% endfor %}
							</ul>
						{% endif %}
					</div>
				</form>

			{% endif %}
			
		</div>
	</div>

{% endblock content %}

{% block domready %}

	const deptOptions = document.querySelectorAll('#id_department option');
	const levelOptions = document.querySelectorAll('#id_level option');
	deptOptions.forEach(function(option) {
		if (option.textContent == "{{request.user.student.department}}") {
			option.selected = true;
		};
	});
	levelOptions.forEach(function(level) {
		if (level.textContent == "{{request.user.student.level}}") {
			level.selected = true;
		};
	});

{% endblock domready %}

spa/templates/spa/project-delete.html
{% extends 'base.html' %}

{% block title %}Delete Project Confirmation{% endblock title %}

{% block content %}
	
	<h2 class="mt-3 text-center">Delete Project</h2>
	<div class="d-flex flex-column align-items-center mt-4">
		<h4>Are You Sure You Want To Delete "{{object.title}} Project"?</h4>
		<form method="post">
			{% csrf_token %}
			<a href="javascript:history.back()" class="btn btn-outline-primary">Go Back</a>
			<button type="submit" class="btn btn-danger ml-2">Yes, Logout</button>
		</form>
	</div>

{% endblock content %}

spa/templates/spa/student-dashboard.html
{% extends 'base.html' %}

{% block title %}
	{% if request.user == user %}
		Your 
	{% else %}
		{{user.first_name | title}}'s
	{% endif %} 
	Dashboard
{% endblock title %}

{% block content %}
	
	<h2 class="text-center mt-4 mb-3">Dashboard</h2>
	<div class="row">
		<div class="col-lg-6 px-5 py-5">
			<h5 class="mb-2">
				{% if request.user == user %}
				Your 
				{% else %}
				{{user.first_name | title}}'s
				{% endif %}
				Profile:
			</h5>
			
				
			<div class="fieldWrapper form-group">
				<label for="id_first_name">First Name:</label>
				<div class="form-group">
					<input disabled type="text" name="first_name" id="id_first_name" placeholder="First Name" class="form-control" value="{{user.first_name}}">
					<i class="fa-solid fa-circle-user input-icon"></i>
				</div>
			</div>
			<div class="fieldWrapper form-group">
				<label for="id_last_name">Last Name:</label>
				<div class="form-group">
					<input disabled type="text" name="last_name" id="id_last_name" placeholder="Last Name" class="form-control" value="{{user.last_name}}">
					<i class="fa-solid fa-circle-user input-icon"></i>
				</div>
			</div>
			<div class="fieldWrapper form-group">
				<label for="id_reg_no">Reg. No.:</label>
				<div class="form-group">
					<input disabled type="text" name="reg_no" id="id_reg_no" placeholder="Reg No" class="form-control"  value="{{user.student.reg_no}}">
					<i class="fa-solid fa-circle-user input-icon"></i>
				</div>
			</div>

			<div class="fieldWrapper form-group">
				<label for="id_department">Department:</label>
				<div class="form-group">
					<input disabled type="text" name="department" id="id_department" class="form-control"  value="{{user.student.department}}">
					<i class="fa-regular fa-address-card input-icon"></i>
				</div>
			</div>
			<div class="fieldWrapper form-group">
				<label for="id_level">Level:</label>
				<div class="form-group">
					<input disabled type="text" name="level" id="id_level" class="form-control"  value="{{user.student.level}}">
					<i class="fa-regular fa-address-card input-icon"></i>
				</div>
			</div>
			<div class="fieldWrapper form-group">
				<label for="id_Email">Email:</label>
				<div class="form-group">
					<input disabled type="email" name="email" id="id_email" placeholder="Email" class="form-control" value="{{user.email}}">
					<i class="fa-solid fa-envelope input-icon"></i>
				</div>
			</div>
			{% if request.user == user or request.user.is_staff %}
				<div>
					<a href="{% url 'student_update' user.pk %}" class="btn btn-primary">Update Profile</a>
				</div>
			{% endif %}
			
		</div>
		<div class="col-lg-6 px-5 py-lg-5">
			{% if user.student.project == None %}

				<div class="d-flex flex-column align-items-center">
					{% if request.user == user %}
						<h6>You Have Not Registered Your Project</h6>
						<a href="{% url 'register_project' %}" class="btn btn-success">Register Now</a>
					{% else %}
						<h6>{{user.first_name}} Have Not Registered A Project Yet</h6>
					{% endif %} 
					
				</div>

			{% else %}

				<h5 class="mb-2">
					{% if request.user == user %}
						Your 
					{% else %}
						{{user.first_name | title}}'s
					{% endif %}
					Project:
				</h5>
				
				<div class="fieldWrapper form-group">
					<label for="{{p_form.title.id_for_title}}">Title</label>
					<div class="form-group">
						<input type="text" disabled name="title" id="id_title" class="form-control" value="{{user.student.project.title}}">
						<i class="fa-solid fa-pen input-icon"></i>
					</div>
				</div>
				<div class="fieldWrapper form-group">
					<label for="{{p_form.case_study.id_for_case_study}}">Case Study</label>
					<div class="form-group">
						<input type="text" disabled name="case_study" id="id_case_study" class="form-control" value="{{user.student.project.case_study}}">
						<i class="fa-solid fa-pen input-icon"></i>
					</div>
				</div>
				
				<a href="{% url 'project_detail' user.student.project.pk %}" class="btn btn-primary">View Project</a>

			{% endif %}
		</div>
		
	</div>

{% endblock content %}
